check:
  - thoth-build
build:
  build-stratergy: "Dockerfile"
  dockerfile-path: "build/Dockerfile.multistage"
  registry: "quay.io"
  registry-org: "harshad16"
  registry-project: "opendatahub-operator"
  registry-secret: "thoth-station-thoth-pusher-secret"
